import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ApplyOnceLogo } from '../../components/ApplyOnceLogo'
import { Navbar } from '../../components/Navbar'
import { downloadBlob, makeSimpleTextPdf } from './pdfHelpers'

type Answers = {
  fullName: string
  funderName: string
  whereFrom: string
  familyContext: string
  personality: string
  strengths: string
  hobbies: string
  achievements: string
  course: string
  university: string
  whyCourse: string
  careerVision: string
  whyFunding: string
  leadership: string
  closing: string
}

const empty = (): Answers => ({
  fullName: '',
  funderName: '',
  whereFrom: '',
  familyContext: '',
  personality: '',
  strengths: '',
  hobbies: '',
  achievements: '',
  course: '',
  university: '',
  whyCourse: '',
  careerVision: '',
  whyFunding: '',
  leadership: '',
  closing: '',
})

function buildLetter(a: Answers): string {
  const today = new Date().toLocaleDateString()
  const funderLine = a.funderName.trim() ? `Dear ${a.funderName.trim()} Selection Committee,` : 'Dear Selection Committee,'

  const para = (s: string) => s.trim().replace(/\s+/g, ' ')

  const p1 = para(
    `My name is ${a.fullName || '___'}. I am writing to apply for funding support to pursue ${
      a.course || 'my studies'
    }${a.university ? ` at ${a.university}` : ''}.`,
  )

  const p2Parts = [a.whereFrom, a.familyContext].filter((x) => x.trim())
  const p2 = p2Parts.length
    ? para(`I come from ${a.whereFrom || '___'}. ${a.familyContext}`)
    : para('I come from ___ and I am committed to building a better future for myself and my community.')

  const p3Bits = [a.personality, a.strengths].filter((x) => x.trim())
  const p3 = p3Bits.length
    ? para(`${a.personality} ${a.strengths}`)
    : para('I am disciplined, hardworking, and committed to learning and growth.')

  const p4Bits = [a.hobbies, a.achievements, a.leadership].filter((x) => x.trim())
  const p4 = p4Bits.length
    ? para(
        `Outside the classroom, ${a.hobbies ? a.hobbies.trim() : 'I stay active and involved'}. ${
          a.achievements ? a.achievements.trim() : ''
        } ${a.leadership ? a.leadership.trim() : ''}`.trim(),
      )
    : para('Outside the classroom, I stay involved through school and community activities that build my character.')

  const p5 = a.whyCourse.trim()
    ? para(a.whyCourse)
    : para(
        `I chose ${a.course || 'this course'} because it matches my strengths and interests, and it creates a real pathway to a stable career.`,
      )

  const p6 = a.careerVision.trim()
    ? para(a.careerVision)
    : para(
        'My long-term goal is to build a career where I can support my family, contribute to South Africa, and grow into a leader in my field.',
      )

  const p7 = a.whyFunding.trim()
    ? para(a.whyFunding)
    : para(
        'I am applying for this bursary because financial support would remove barriers and allow me to focus on my studies and perform at my best.',
      )

  const p8 = a.closing.trim()
    ? para(a.closing)
    : para('Thank you for considering my application. I would be honoured to represent your organisation with excellence.')

  return [
    today,
    '',
    funderLine,
    '',
    p1,
    '',
    p2,
    '',
    p3,
    '',
    p4,
    '',
    p5,
    '',
    p6,
    '',
    p7,
    '',
    p8,
    '',
    'Sincerely,',
    a.fullName || '___',
  ].join('\n')
}

export function ResourceMotivationLetterPage() {
  const [answers, setAnswers] = useState<Answers>(() => {
    try {
      const raw = localStorage.getItem('apply_once_motivation_letter')
      if (!raw) return empty()
      return { ...empty(), ...(JSON.parse(raw) as Partial<Answers>) }
    } catch {
      return empty()
    }
  })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const letter = useMemo(() => buildLetter(answers), [answers])

  function update<K extends keyof Answers>(key: K, value: string) {
    setAnswers((prev) => {
      const next = { ...prev, [key]: value }
      localStorage.setItem('apply_once_motivation_letter', JSON.stringify(next))
      return next
    })
  }

  async function onDownload() {
    setBusy(true)
    setError(null)
    try {
      const bytes = await makeSimpleTextPdf({
        title: 'Motivation Letter',
        subtitle: 'Generated by Apply Once resources. Review and edit for each bursary before submitting.',
        blocks: [{ text: letter }],
      })
      downloadBlob(bytes, 'apply-once-motivation-letter.pdf')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not generate PDF')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="formShell resourcesShell" id="top">
      <Navbar
        variant="light"
        logo={<ApplyOnceLogo />}
        links={[
          { label: 'Features', to: '/#features' },
          { label: 'Resources', to: '/resources' },
        ]}
      />
      <main className="resourcesToolMain">
        <div className="container resourcesContainer">
          <nav className="resourcesCrumb">
            <Link to="/resources">Resources</Link>
            <span aria-hidden>/</span>
            <span>Motivation letter builder</span>
          </nav>

          <header className="resourcesToolHero">
            <h1 className="resourcesToolTitle">Motivation letter builder</h1>
            <p className="resourcesToolLead">
              Answer the prompts and we’ll turn it into a professional bursary motivation letter. Keep it honest and
              specific.
            </p>
          </header>

          <div className="resourcesSplit">
            <section className="resourcesToolCard">
              <div className="resourcesToolRow">
                <h2 className="resourcesToolCardTitle">Your answers</h2>
                <button type="button" className="btn btnOutline btnSmall" onClick={() => setAnswers(empty())}>
                  Clear
                </button>
              </div>

              <div className="resourcesForm">
                <label className="field">
                  <span>Your full name</span>
                  <input value={answers.fullName} onChange={(e) => update('fullName', e.target.value)} />
                </label>
                <label className="field">
                  <span>Funder name (optional)</span>
                  <input
                    value={answers.funderName}
                    onChange={(e) => update('funderName', e.target.value)}
                    placeholder="e.g. Sasol Bursary"
                  />
                </label>
                <label className="field">
                  <span>Where are you from?</span>
                  <textarea
                    rows={3}
                    value={answers.whereFrom}
                    onChange={(e) => update('whereFrom', e.target.value)}
                    placeholder="Township / village / city and province, and what shaped you."
                  />
                </label>
                <label className="field">
                  <span>Family & home life context</span>
                  <textarea
                    rows={3}
                    value={answers.familyContext}
                    onChange={(e) => update('familyContext', e.target.value)}
                    placeholder="Brief, respectful context about responsibilities or challenges you overcame."
                  />
                </label>
                <label className="field">
                  <span>Personality</span>
                  <textarea
                    rows={3}
                    value={answers.personality}
                    onChange={(e) => update('personality', e.target.value)}
                    placeholder="How would teachers/friends describe you?"
                  />
                </label>
                <label className="field">
                  <span>Strengths</span>
                  <textarea
                    rows={3}
                    value={answers.strengths}
                    onChange={(e) => update('strengths', e.target.value)}
                    placeholder="Academic strengths, skills, and what you consistently do well."
                  />
                </label>
                <label className="field">
                  <span>Hobbies / activities</span>
                  <textarea rows={3} value={answers.hobbies} onChange={(e) => update('hobbies', e.target.value)} />
                </label>
                <label className="field">
                  <span>Achievements</span>
                  <textarea
                    rows={3}
                    value={answers.achievements}
                    onChange={(e) => update('achievements', e.target.value)}
                    placeholder="Awards, top subjects, leadership roles, community impact."
                  />
                </label>
                <div className="fieldRow">
                  <label className="field">
                    <span>Course / programme</span>
                    <input value={answers.course} onChange={(e) => update('course', e.target.value)} />
                  </label>
                  <label className="field">
                    <span>Institution (optional)</span>
                    <input value={answers.university} onChange={(e) => update('university', e.target.value)} />
                  </label>
                </div>
                <label className="field">
                  <span>Why did you pick this course?</span>
                  <textarea rows={4} value={answers.whyCourse} onChange={(e) => update('whyCourse', e.target.value)} />
                </label>
                <label className="field">
                  <span>Your aspirations / career vision</span>
                  <textarea
                    rows={4}
                    value={answers.careerVision}
                    onChange={(e) => update('careerVision', e.target.value)}
                  />
                </label>
                <label className="field">
                  <span>Why do you need funding?</span>
                  <textarea
                    rows={4}
                    value={answers.whyFunding}
                    onChange={(e) => update('whyFunding', e.target.value)}
                  />
                </label>
                <label className="field">
                  <span>Leadership & community (optional)</span>
                  <textarea
                    rows={3}
                    value={answers.leadership}
                    onChange={(e) => update('leadership', e.target.value)}
                    placeholder="Examples: tutoring, volunteering, prefect, sports captain, church/youth group."
                  />
                </label>
                <label className="field">
                  <span>Closing message (optional)</span>
                  <textarea rows={3} value={answers.closing} onChange={(e) => update('closing', e.target.value)} />
                </label>
              </div>
            </section>

            <section className="resourcesToolCard">
              <div className="resourcesToolRow">
                <h2 className="resourcesToolCardTitle">Preview</h2>
                <button type="button" className="btn btnBrand btnSmall" disabled={busy} onClick={() => void onDownload()}>
                  {busy ? 'Creating PDF…' : 'Download PDF'}
                </button>
              </div>
              {error ? <div className="formError">{error}</div> : null}
              <pre className="resourcesPreview">{letter}</pre>
              <p className="muted">
                Tip: the strongest letters include numbers and proof (results, awards, hours volunteered, leadership
                roles, responsibilities at home).
              </p>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}

